---

version: "3.8"

services:
  database:
    image: postgres:14-alpine
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    volumes:
      - ./:/home/ubuntu/service
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

volumes:
  db_data: { }